### ISSUE TITLE
Problem with Dataflowmethod() 

### ISSUE THREAD

**Issue by JulianVeit** [mingjerli/IMFData#21]
Hey!  Last friday getting data via the IMFData package worked perfectly fine. However, today this new error message is popping up when trying to run the DataflowMethod() function.

> library(IMFData)
> availableDB <- DataflowMethod()
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Recv failure: Connection was reset
Called from: curl::curl_fetch_memory(url, handle = handle)

Also this curl_fetch_memory file is popping up:

function (url, handle = new_handle()) 
{
  nonblocking <- isTRUE(getOption("curl_interrupt", TRUE))
  output <- .Call(R_curl_fetch_memory, enc2utf8(url), handle, 
    nonblocking)
  res <- handle_data(handle)
  res$content <- output
  res
}

Any help or comments are appreciated very much!

Thanks!

Julian 

PS: Also does anyone know why the 'IMFData''  (and also the 'imfr') package is not in the CRAN repository anymore? Thanks!

**Comment by mingjerli** [comment]
The package have not been maintained for more than five years. Usually when things broken (something happen on IMF side), just wait one or two days, it should resolve. Since I don't work for IMF now, I have no way to verify what's going on with these endpoints anymore.

I believe there were some requirements need to meet to keep the package in CRAN earlier this year. Since I haven't write any line of R for more than five years personally, I just don't feel the need to do it.

**Comment by JulianVeit** [comment]
Alright thank you for your fast response! Today it worked again so I am very relieved! It is a little pity that the package is not maintained as I am lokking for a stable way of retrieving data from the IMF and also the other package called "imfr" seems to not be maintained. I am wondering a bit about that becauseit is definitely a very usefool sort of package to have!

Thanks anyway for your response and also your great work for the package!

Best regards

Julian
